import type { Mission, Node, TheoryCard } from '../domain/types';

export const missions: Mission[] = [
  {
    id: 'mission.percentages.market_discounts',
    moduleId: 'module.proportionality_finance',
    title: 'Mercado de descuentos imposibles',
    narrativeTitle: 'Expedición al Mercado de Proporciones',
    learningGoal: 'Calcular descuentos y distinguir cantidad descontada de precio final.',
    estimatedMinutes: 12,
    prerequisites: [],
    nodeIds: ['node.percentages.calculate_part', 'node.percentages.final_price_after_discount'],
    theoryCardIds: ['theory.percentages.discount_basics'],
    exerciseIds: ['exercise.mv-2eso-a5-percentages-001'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '6.1'] },
  },
  {
    id: 'mission.equations.balance_lab',
    moduleId: 'module.algebra_functions',
    title: 'Laboratorio de la balanza',
    learningGoal: 'Resolver ecuaciones lineales sencillas y comprobar la solución por sustitución.',
    estimatedMinutes: 10,
    prerequisites: [],
    nodeIds: ['node.equations.linear_simple_solution', 'node.equations.substitution_check'],
    theoryCardIds: ['theory.equations.balance_basics'],
    exerciseIds: ['exercise.mv-2eso-d4-equations-001'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4'], competencies: ['CE1', 'CE2', 'CE7'], criteria: ['1.1', '2.2', '7.1'] },
  },
];

export const nodes: Node[] = [
  {
    id: 'node.percentages.calculate_part',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Calcular una parte porcentual',
    description: 'Traducir un porcentaje a una cantidad concreta.',
    skillFamily: 'porcentajes',
    difficultyRange: [1, 3],
    prerequisites: [],
    commonErrorCodes: ['parte_vs_final'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2'], competencies: ['CE1'], criteria: ['1.1'] },
  },
  {
    id: 'node.percentages.final_price_after_discount',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Distinguir descuento y precio final',
    description: 'Leer con precisión si se pide rebaja, aumento o precio final.',
    skillFamily: 'porcentajes',
    difficultyRange: [2, 4],
    prerequisites: ['node.percentages.calculate_part'],
    commonErrorCodes: ['parte_vs_final'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2'], competencies: ['CE1', 'CE6'], criteria: ['1.3'] },
  },
  {
    id: 'node.equations.linear_simple_solution',
    moduleId: 'module.algebra_functions',
    missionIds: ['mission.equations.balance_lab'],
    title: 'Resolver una ecuación lineal sencilla',
    description: 'Aislar la incógnita usando operaciones inversas.',
    skillFamily: 'ecuaciones',
    difficultyRange: [1, 3],
    prerequisites: [],
    commonErrorCodes: ['equations.inverse_operation_error'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4'], competencies: ['CE1'], criteria: ['1.1'] },
  },
  {
    id: 'node.equations.substitution_check',
    moduleId: 'module.algebra_functions',
    missionIds: ['mission.equations.balance_lab'],
    title: 'Comprobar por sustitución',
    description: 'Sustituir la solución para verificar la igualdad.',
    skillFamily: 'ecuaciones',
    difficultyRange: [1, 3],
    prerequisites: ['node.equations.linear_simple_solution'],
    commonErrorCodes: [],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4'], competencies: ['CE2'], criteria: ['2.2'] },
  },
];

export const theoryCards: TheoryCard[] = [
  {
    id: 'theory.percentages.discount_basics',
    nodeIds: ['node.percentages.calculate_part', 'node.percentages.final_price_after_discount'],
    title: 'Porcentajes en descuentos',
    body: 'Un porcentaje compara una parte con 100. Para calcular el 25 % de 40, convierte 25 % en 0,25 y multiplica 40 · 0,25.',
    workedExample: 'Si algo cuesta 40 € y se descuenta el 25 %, el descuento es 10 € y el precio final es 30 €.',
    commonMistake: 'Confundir la cantidad descontada con el precio final.',
  },
  {
    id: 'theory.equations.balance_basics',
    nodeIds: ['node.equations.linear_simple_solution'],
    title: 'Ecuaciones como balanzas',
    body: 'Para mantener la igualdad, cualquier operación que haces a un lado se hace también al otro.',
    workedExample: '3x + 5 = 17; restamos 5: 3x = 12; dividimos entre 3: x = 4.',
    commonMistake: 'Quitar un término con la operación equivocada.',
  },
];
