import type { Module } from '../domain/types';

export const modules: Module[] = [
  {
    id: 'module.numbers_port',
    title: 'Números, cálculo y estimación',
    territoryName: 'Puerto de los Números',
    description: 'Cálculo, divisibilidad, estimación y sentido numérico.',
    curriculumSense: 'A',
    knowledgeCodes: ['MAT.2.A'],
    competencies: ['CE1', 'CE2'],
    criteria: ['1.1', '2.1'],
    missionIds: [],
    status: 'partial',
  },
  {
    id: 'module.proportionality_finance',
    title: 'Proporcionalidad, porcentajes y educación financiera',
    territoryName: 'Mercado de Proporciones',
    description: 'Razones, porcentajes, aumentos, descuentos, IVA, escalas y decisiones cotidianas.',
    curriculumSense: 'A',
    knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.1', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'],
    competencies: ['CE1', 'CE2', 'CE6', 'CE7'],
    criteria: ['1.1', '1.3', '2.2', '6.1', '7.2'],
    missionIds: ['mission.percentages.market_discounts'],
    status: 'available',
    recommendedFirstMissionId: 'mission.percentages.market_discounts',
  },
  {
    id: 'module.measurement_workshop',
    title: 'Magnitudes, áreas, volúmenes y precisión',
    territoryName: 'Taller de Medidas',
    description: 'Medir, estimar y razonar con magnitudes.',
    curriculumSense: 'B',
    knowledgeCodes: ['MAT.2.B'],
    competencies: ['CE1', 'CE2'],
    criteria: ['1.1', '2.2'],
    missionIds: [],
    status: 'coming_soon',
  },
  {
    id: 'module.geometry_archipelago',
    title: 'Figuras, Pitágoras, semejanza y coordenadas',
    territoryName: 'Archipiélago Geométrico',
    description: 'Geometría para orientarse, medir y justificar.',
    curriculumSense: 'C',
    knowledgeCodes: ['MAT.2.C'],
    competencies: ['CE1', 'CE6'],
    criteria: ['1.2', '6.1'],
    missionIds: [],
    status: 'coming_soon',
  },
  {
    id: 'module.algebra_functions',
    title: 'Variable, ecuaciones, sistemas y funciones',
    territoryName: 'Laboratorio Algebraico',
    description: 'Usar incógnitas para describir y resolver relaciones.',
    curriculumSense: 'D',
    knowledgeCodes: ['MAT.2.D.4'],
    competencies: ['CE1', 'CE2', 'CE7'],
    criteria: ['1.1', '2.2', '7.1'],
    missionIds: ['mission.equations.balance_lab'],
    status: 'partial',
  },
  {
    id: 'module.strategy_notebook',
    title: 'Error, comprobación, perseverancia y comunicación matemática',
    territoryName: 'Cuaderno del Estratega',
    description: 'Revisión de errores útiles y estrategias transversales.',
    curriculumSense: 'F',
    knowledgeCodes: ['MAT.2.F'],
    competencies: ['CE6', 'CE7', 'CE8'],
    criteria: ['6.1', '7.2', '8.1'],
    missionIds: [],
    status: 'extension',
  },
];
