import type { ContentSeed, Exercise, Mission, Module, SkillNode, TheoryCard } from '../domain/types';

export const CONTENT_VERSION = 'mv-local-0';

export const modules: Module[] = [
  {
    id: 'module.numbers_calculation_estimation',
    title: 'Números, cálculo y estimación',
    territoryName: 'Puerto de los Números',
    description: 'Enteros, fracciones, decimales, raíces, notación científica, estimación, operaciones, factores y representación numérica.',
    curriculumSense: 'A',
    knowledgeCodes: ['MAT.2.A.1.1', 'MAT.2.A.1.2', 'MAT.2.A.2.1', 'MAT.2.A.2.2', 'MAT.2.A.2.3', 'MAT.2.A.2.4', 'MAT.2.A.3.1', 'MAT.2.A.3.2', 'MAT.2.A.3.3', 'MAT.2.A.3.4', 'MAT.2.A.3.5', 'MAT.2.A.4.1', 'MAT.2.A.4.2'],
    competencies: ['CE1', 'CE2', 'CE4', 'CE5', 'CE7', 'CE8'],
    criteria: ['1.1', '1.2', '1.3', '2.1', '4.1', '5.2', '7.1', '8.2'],
    missionIds: [],
    status: 'coming_soon',
  },
  {
    id: 'module.proportionality_finance',
    title: 'Proporcionalidad, porcentajes y educación financiera',
    territoryName: 'Mercado de Proporciones',
    description: 'Razones, porcentajes, aumentos, descuentos, IVA, escalas, cambios de divisa, velocidad y decisiones de consumo responsable.',
    curriculumSense: 'A',
    knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.1', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'],
    competencies: ['CE1', 'CE2', 'CE5', 'CE6', 'CE7', 'CE8', 'CE9'],
    criteria: ['1.1', '1.3', '2.2', '5.2', '6.1', '7.2', '8.2', '9.2'],
    missionIds: ['mission.percentages.market_discounts'],
    status: 'available',
    recommendedFirstMissionId: 'mission.percentages.market_discounts',
  },
  {
    id: 'module.measurement_precision',
    title: 'Medida, áreas, volúmenes y precisión',
    territoryName: 'Taller de Medidas',
    description: 'Magnitudes, elección de unidades, longitudes, áreas, volúmenes, representaciones planas de cuerpos y precisión necesaria.',
    curriculumSense: 'B',
    knowledgeCodes: ['MAT.2.B.1.1', 'MAT.2.B.1.2', 'MAT.2.B.2.1', 'MAT.2.B.2.2', 'MAT.2.B.2.3', 'MAT.2.B.3'],
    competencies: ['CE1', 'CE2', 'CE3', 'CE7'],
    criteria: ['2.2', '3.1', '7.1', '7.2'],
    missionIds: [],
    status: 'coming_soon',
  },
  {
    id: 'module.geometry_space',
    title: 'Geometría y espacio',
    territoryName: 'Archipiélago Geométrico',
    description: 'Figuras planas y tridimensionales, congruencia, semejanza, relación pitagórica, proporción cordobesa, coordenadas y modelización geométrica.',
    curriculumSense: 'C',
    knowledgeCodes: ['MAT.2.C.1.1', 'MAT.2.C.1.2', 'MAT.2.C.1.3', 'MAT.2.C.2', 'MAT.2.C.3.1', 'MAT.2.C.3.2'],
    competencies: ['CE3', 'CE4', 'CE5', 'CE6', 'CE7'],
    criteria: ['3.3', '4.2', '5.1', '6.2', '7.1'],
    missionIds: [],
    status: 'coming_soon',
  },
  {
    id: 'module.algebra_equations_functions',
    title: 'Álgebra, ecuaciones, sistemas y funciones',
    territoryName: 'Laboratorio Algebraico',
    description: 'Patrones, variable, lenguaje algebraico, ecuaciones, sistemas, relaciones lineales y cuadráticas, tablas, gráficas, fórmulas y algoritmos.',
    curriculumSense: 'D',
    knowledgeCodes: ['MAT.2.D.1', 'MAT.2.D.2.1', 'MAT.2.D.2.2', 'MAT.2.D.3', 'MAT.2.D.4.1', 'MAT.2.D.4.2', 'MAT.2.D.4.3', 'MAT.2.D.4.4', 'MAT.2.D.5.1', 'MAT.2.D.5.2', 'MAT.2.D.5.3', 'MAT.2.D.6.1', 'MAT.2.D.6.2', 'MAT.2.D.6.3'],
    competencies: ['CE2', 'CE3', 'CE4', 'CE5', 'CE6', 'CE8'],
    criteria: ['2.1', '3.1', '3.2', '4.1', '4.2', '6.2', '8.1', '8.2'],
    missionIds: ['mission.algebra.linear_equations_brief'],
    status: 'partial',
    recommendedFirstMissionId: 'mission.algebra.linear_equations_brief',
  },
  {
    id: 'module.strategy_error_identity',
    title: 'Estrategia, error, colaboración e identidad matemática',
    territoryName: 'Cuaderno del Estratega',
    description: 'Gestión emocional, perseverancia, flexibilidad cognitiva, error útil, revisión, trabajo cooperativo, inclusión y contribución andaluza a las matemáticas.',
    curriculumSense: 'F',
    knowledgeCodes: ['MAT.2.F.1.1', 'MAT.2.F.1.2', 'MAT.2.F.1.3', 'MAT.2.F.2.1', 'MAT.2.F.2.2', 'MAT.2.F.3.1', 'MAT.2.F.3.2', 'MAT.2.F.3.3'],
    competencies: ['CE9', 'CE10', 'CE6', 'CE8'],
    criteria: ['6.3', '9.1', '9.2', '10.1', '10.2'],
    missionIds: [],
    status: 'partial',
  },
];

export const skillNodes: SkillNode[] = [
  {
    id: 'node.percentages.meaning',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Interpretar el porcentaje como relación sobre 100',
    description: 'Reconocer que a % significa a de cada 100 y puede representarse como decimal o fracción.',
    skillFamily: 'porcentajes',
    difficultyRange: [1, 2],
    prerequisites: [],
    commonErrorCodes: ['percent_as_whole_number'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.1'], competencies: ['CE6', 'CE8'], criteria: ['6.1', '8.2'] },
  },
  {
    id: 'node.percentages.calculate_part',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Calcular la parte porcentual de una cantidad',
    description: 'Obtener cuánto vale un porcentaje de una cantidad de referencia.',
    skillFamily: 'porcentajes',
    difficultyRange: [1, 3],
    prerequisites: ['node.percentages.meaning'],
    commonErrorCodes: ['parte_vs_final', 'percent_division_error'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2'], competencies: ['CE1', 'CE6'], criteria: ['1.3', '6.1'] },
  },
  {
    id: 'node.percentages.final_price_after_change',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Calcular precio final tras descuento, aumento o IVA',
    description: 'Distinguir entre cantidad descontada o aumentada y valor final de la situación.',
    skillFamily: 'porcentajes',
    difficultyRange: [2, 4],
    prerequisites: ['node.percentages.calculate_part'],
    commonErrorCodes: ['parte_vs_final', 'wrong_reference_amount'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE1', 'CE2', 'CE6', 'CE7'], criteria: ['1.1', '1.3', '2.2', '6.1', '7.2'] },
  },
  {
    id: 'node.percentages.calculate_total',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Recuperar la cantidad inicial o total',
    description: 'Calcular el total cuando se conoce una parte porcentual o un precio final tras variación.',
    skillFamily: 'porcentajes',
    difficultyRange: [3, 4],
    prerequisites: ['node.percentages.calculate_part'],
    commonErrorCodes: ['wrong_reference_amount'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2', 'MAT.2.A.5.3'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '2.2', '6.1'] },
  },
  {
    id: 'node.percentages.compare_offers',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Comparar ofertas y tomar decisiones de consumo',
    description: 'Comparar precios finales, descuentos e impuestos para decidir con criterio matemático.',
    skillFamily: 'educacion_financiera',
    difficultyRange: [3, 4],
    prerequisites: ['node.percentages.final_price_after_change'],
    commonErrorCodes: ['add_percentages_without_reference', 'ignores_units_or_context'],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE2', 'CE6', 'CE9'], criteria: ['2.2', '6.1', '9.2'] },
  },
  {
    id: 'node.strategy.repair_percent_reference',
    moduleId: 'module.strategy_error_identity',
    missionIds: ['mission.percentages.market_discounts'],
    title: 'Reparar la confusión entre parte, total y precio final',
    description: 'Usar el error como pista: separar qué se pregunta, qué cantidad es la referencia y qué magnitud se obtiene.',
    skillFamily: 'error_util',
    difficultyRange: [1, 3],
    prerequisites: [],
    commonErrorCodes: ['parte_vs_final', 'wrong_reference_amount'],
    curriculum: { sense: 'F', knowledgeCodes: ['MAT.2.F.1.2', 'MAT.2.F.1.3'], competencies: ['CE9'], criteria: ['9.2'] },
  },
  {
    id: 'node.algebra.solve_one_step_add_subtract',
    moduleId: 'module.algebra_equations_functions',
    missionIds: ['mission.algebra.linear_equations_brief'],
    title: 'Resolver ecuaciones de un paso con suma y resta',
    description: 'Aislar la incógnita deshaciendo sumas o restas en ambos miembros.',
    skillFamily: 'ecuaciones_lineales',
    difficultyRange: [1, 2],
    prerequisites: [],
    commonErrorCodes: ['equations.inverse_operation_error', 'equations.sign_error'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1', 'MAT.2.D.4.2'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'node.algebra.solve_one_step_multiply_divide',
    moduleId: 'module.algebra_equations_functions',
    missionIds: ['mission.algebra.linear_equations_brief'],
    title: 'Resolver ecuaciones de un paso con producto y división',
    description: 'Despejar la incógnita dividiendo o multiplicando por el coeficiente correcto.',
    skillFamily: 'ecuaciones_lineales',
    difficultyRange: [1, 2],
    prerequisites: ['node.algebra.solve_one_step_add_subtract'],
    commonErrorCodes: ['equations.coefficient_division_error'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1', 'MAT.2.D.4.2'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'node.algebra.solve_two_step_basic',
    moduleId: 'module.algebra_equations_functions',
    missionIds: ['mission.algebra.linear_equations_brief'],
    title: 'Resolver ecuaciones lineales de dos pasos',
    description: 'Aplicar el orden inverso de operaciones para aislar la incógnita.',
    skillFamily: 'ecuaciones_lineales',
    difficultyRange: [2, 3],
    prerequisites: ['node.algebra.solve_one_step_multiply_divide'],
    commonErrorCodes: ['equations.inverse_operation_error', 'equations.sign_error'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.2', 'MAT.2.D.4.3'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.2'] },
  },
  {
    id: 'node.algebra.check_solution_substitution',
    moduleId: 'module.algebra_equations_functions',
    missionIds: ['mission.algebra.linear_equations_brief'],
    title: 'Comprobar soluciones por sustitución',
    description: 'Verificar que el valor obtenido mantiene la igualdad al sustituir.',
    skillFamily: 'verificacion_algebraica',
    difficultyRange: [1, 3],
    prerequisites: ['node.algebra.solve_two_step_basic'],
    commonErrorCodes: ['equations.solution_not_checked'],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.6.1'], competencies: ['CE6'], criteria: ['6.2'] },
  },
  {
    id: 'node.strategy.repair_inverse_operation',
    moduleId: 'module.strategy_error_identity',
    missionIds: ['mission.algebra.linear_equations_brief'],
    title: 'Reparar errores de operación inversa y signo',
    description: 'Corregir el paso de despeje cuando se aplica la operación equivocada o se pierde un signo.',
    skillFamily: 'error_util',
    difficultyRange: [1, 3],
    prerequisites: [],
    commonErrorCodes: ['equations.inverse_operation_error', 'equations.sign_error', 'equations.coefficient_division_error'],
    curriculum: { sense: 'F', knowledgeCodes: ['MAT.2.F.1.2', 'MAT.2.F.1.3'], competencies: ['CE9'], criteria: ['9.2'] },
  },
];

export const theoryCards: TheoryCard[] = [
  {
    id: 'theory.percentages.discount_basics',
    nodeIds: ['node.percentages.meaning', 'node.percentages.calculate_part', 'node.percentages.final_price_after_change'],
    title: 'Porcentaje, descuento y precio final',
    body: 'Un porcentaje compara una cantidad con 100. Para calcular el a % de una cantidad, transforma a % en decimal y multiplica por la cantidad de referencia. En descuentos hay dos magnitudes distintas: lo que se descuenta y el precio final.',
    workedExample: {
      statement: 'Un juego cuesta 40 € y tiene un descuento del 25 %.',
      steps: ['25 % = 0,25.', 'Descuento: 40 · 0,25 = 10 €.', 'Precio final: 40 − 10 = 30 €.'],
      answer: 'Se descuentan 10 € y se paga 30 €.',
    },
    commonMistake: 'Responder 30 € cuando se pregunta por el descuento, o responder 10 € cuando se pregunta por el precio final.',
    strategyCardIds: ['strategy.read_what_is_asked', 'strategy.estimate_before_answer'],
  },
  {
    id: 'theory.algebra.linear_equation_basics',
    nodeIds: ['node.algebra.solve_one_step_add_subtract', 'node.algebra.solve_two_step_basic'],
    title: 'Resolver ecuaciones como una balanza',
    body: 'Resolver una ecuación es encontrar el valor de la incógnita que mantiene verdadera la igualdad. Para despejar, deshaz operaciones en orden inverso y conserva el equilibrio en ambos miembros.',
    workedExample: {
      statement: '2x + 3 = 17',
      steps: ['Resta 3 en ambos lados: 2x = 14.', 'Divide entre 2: x = 7.', 'Comprueba sustituyendo: 2·7 + 3 = 17.'],
      answer: 'x = 7',
    },
    commonMistake: 'Mover un término de lado sin aplicar la operación inversa, o no comprobar la solución al final.',
    strategyCardIds: ['strategy.algebra.substitute_before_continue'],
  },
];

export const missions: Mission[] = [
  {
    id: 'mission.percentages.market_discounts',
    moduleId: 'module.proportionality_finance',
    title: 'Mercado de descuentos imposibles',
    narrativeTitle: 'Recorre un mercado donde las ofertas solo se abren si distingues descuento, impuesto y precio final.',
    learningGoal: 'Resolver descuentos, aumentos e IVA usando porcentajes como relaciones multiplicativas y comprobando la coherencia del resultado.',
    estimatedMinutes: 12,
    prerequisites: [],
    nodeIds: [
      'node.percentages.meaning',
      'node.percentages.calculate_part',
      'node.percentages.final_price_after_change',
      'node.percentages.calculate_total',
      'node.percentages.compare_offers',
      'node.strategy.repair_percent_reference',
    ],
    theoryCardIds: ['theory.percentages.discount_basics'],
    exerciseIds: [
      'exercise.mv-2eso-a5-percentages-001',
      'exercise.mv-2eso-a5-percentages-002',
      'exercise.mv-2eso-a5-percentages-003',
      'exercise.mv-2eso-a5-percentages-004',
      'exercise.mv-2eso-a5-percentages-005',
      'exercise.mv-2eso-a5-percentages-006',
      'exercise.mv-2eso-a5-percentages-007',
      'exercise.mv-2eso-a5-percentages-008',
      'exercise.mv-2eso-a5-percentages-009',
      'exercise.mv-2eso-a5-percentages-010',
      'exercise.mv-2eso-a5-percentages-011',
      'exercise.mv-2eso-a5-percentages-012',
    ],
    exercisePool: [
      { nodeId: 'node.percentages.calculate_part', minItems: 3, maxItems: 4, difficulties: [1, 2] },
      { nodeId: 'node.percentages.final_price_after_change', minItems: 3, maxItems: 4, difficulties: [2, 3] },
      { nodeId: 'node.percentages.calculate_total', minItems: 2, maxItems: 3, difficulties: [2, 3] },
      { nodeId: 'node.percentages.compare_offers', minItems: 2, maxItems: 2, difficulties: [3] },
      { nodeId: 'node.strategy.repair_percent_reference', minItems: 2, maxItems: 2, difficulties: [1, 2] },
    ],
    successRule: { minNodeMastery: 0.75, minCorrectAnswers: 5, requiresRepairedError: true },
    rewards: [
      { id: 'reward.strategy.read_what_is_asked', title: 'Carta de estrategia: lee qué se pregunta', kind: 'strategy_card', description: 'Recordatorio para separar cantidad inicial, variación y resultado final.' },
      { id: 'reward.badge.error_repaired', title: 'Error convertido en pista', kind: 'badge', description: 'Se obtiene al reparar una confusión entre descuento y precio final.' },
    ],
    repairPolicy: {
      triggerErrorCodes: ['parte_vs_final', 'wrong_reference_amount'],
      repairNodeIds: ['node.strategy.repair_percent_reference'],
      message: 'Antes de seguir, separa la cantidad de referencia, la variación y la magnitud preguntada.',
    },
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE1', 'CE2', 'CE6', 'CE7', 'CE9'], criteria: ['1.1', '1.3', '2.2', '6.1', '7.2', '9.2'] },
    stateForNewLearner: 'available',
  },
  {
    id: 'mission.algebra.linear_equations_brief',
    moduleId: 'module.algebra_equations_functions',
    title: 'Práctica breve: despeja la incógnita',
    narrativeTitle: 'Ajuste de la Balanza',
    learningGoal: 'Resolver ecuaciones lineales de primer grado con una incógnita y comprobar al menos una solución por sustitución.',
    estimatedMinutes: 8,
    prerequisites: [],
    nodeIds: [
      'node.algebra.solve_one_step_add_subtract',
      'node.algebra.solve_one_step_multiply_divide',
      'node.algebra.solve_two_step_basic',
      'node.algebra.check_solution_substitution',
      'node.strategy.repair_inverse_operation',
    ],
    theoryCardIds: ['theory.algebra.linear_equation_basics'],
    exerciseIds: [
      'exercise.mv-2eso-d4-equations-001',
      'exercise.mv-2eso-d4-equations-002',
      'exercise.mv-2eso-d4-equations-003',
      'exercise.mv-2eso-d4-equations-004',
      'exercise.mv-2eso-d4-equations-005',
      'exercise.mv-2eso-d4-equations-006',
      'exercise.mv-2eso-d4-equations-007',
      'exercise.mv-2eso-d4-equations-008',
    ],
    successRule: { minNodeMastery: 0.7, minCorrectAnswers: 5, requiresRepairedError: false },
    rewards: [
      { id: 'reward.strategy.substitute_before_continue', title: 'Carta de estrategia: Sustituye antes de seguir', kind: 'strategy_card', description: 'Recordatorio para verificar al menos una solución en la ecuación original.' },
    ],
    repairPolicy: {
      triggerErrorCodes: ['equations.inverse_operation_error', 'equations.sign_error', 'equations.coefficient_division_error'],
      repairNodeIds: ['node.strategy.repair_inverse_operation'],
      message: 'Antes de continuar, revisa qué operación afecta a x y aplica su inversa en ambos miembros.',
    },
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1', 'MAT.2.D.4.2', 'MAT.2.D.4.3', 'MAT.2.D.6.1'], competencies: ['CE2', 'CE4', 'CE6', 'CE8'], criteria: ['2.1', '4.1', '4.2', '6.2', '8.1'] },
    stateForNewLearner: 'available',
  },
];

const commonPercentHints = [
  { level: 1 as const, text: 'Transforma el porcentaje en decimal: 25 % es 0,25; 15 % es 0,15; 21 % es 0,21.' },
  { level: 2 as const, text: 'Identifica primero qué cantidad es la referencia: el precio inicial, el precio rebajado o el total.' },
];

export const exercises: Exercise[] = [
  {
    id: 'exercise.mv-2eso-a5-percentages-001',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.calculate_part'],
    family: 'porcentaje_parte_total',
    difficulty: 2,
    statement: 'Un videojuego cuesta 40 €. Tiene un descuento del 25 %. ¿Cuánto dinero se descuenta?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 10 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 10, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'El descuento es 40 · 0,25 = 10 €. El precio final sería 30 €, pero aquí se preguntaba cuánto se descuenta.', steps: ['25 % = 0,25', '40 · 0,25 = 10'], check: 'El descuento debe ser menor que el precio inicial.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 30, tolerance: 0.01 }, diagnosis: 'Ha calculado el precio final en lugar del dinero descontado.', feedback: 'Has calculado cuánto se paga después del descuento. La pregunta pide solo cuánto se descuenta.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2'], competencies: ['CE1', 'CE6'], criteria: ['1.3', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-002',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.final_price_after_change'],
    family: 'precio_final_descuento',
    difficulty: 2,
    statement: 'Unas zapatillas cuestan 60 € y tienen una rebaja del 15 %. ¿Cuál es el precio final?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 51 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 51, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'El descuento es 60 · 0,15 = 9 €. El precio final es 60 − 9 = 51 €.', steps: ['15 % = 0,15', '60 · 0,15 = 9', '60 − 9 = 51'], check: 'Como hay rebaja, el precio final debe ser menor que 60 €.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 9, tolerance: 0.01 }, diagnosis: 'Ha calculado la rebaja, pero no el precio final.', feedback: 'Ese 9 € es la cantidad rebajada. Falta restarla al precio inicial.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-003',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.final_price_after_change'],
    family: 'precio_final_iva',
    difficulty: 3,
    statement: 'Una reparación cuesta 80 € sin IVA. Si se añade un 21 % de IVA, ¿cuánto se paga en total?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 96,80 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 96.8, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'El IVA es 80 · 0,21 = 16,80 €. El total es 80 + 16,80 = 96,80 €.', steps: ['21 % = 0,21', '80 · 0,21 = 16,80', '80 + 16,80 = 96,80'], check: 'Como se añade IVA, el total debe ser mayor que 80 €.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 16.8, tolerance: 0.01 }, diagnosis: 'Ha calculado solo el IVA.', feedback: '16,80 € es el IVA añadido. La pregunta pide el total que se paga.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-004',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.calculate_total'],
    family: 'recuperar_precio_inicial',
    difficulty: 3,
    statement: 'Después de una rebaja del 20 %, una mochila cuesta 32 €. ¿Cuál era su precio inicial?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 40 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 40, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'Si se rebaja un 20 %, se paga el 80 % del precio inicial.' },
      { level: 2, text: '32 € corresponde al 80 %. Divide 32 entre 0,80.' },
    ],
    explanation: { text: 'Tras rebajar el 20 %, queda el 80 % del precio. Si 32 = 0,80 · precio inicial, entonces precio inicial = 32 / 0,80 = 40 €.', steps: ['100 % − 20 % = 80 %', '80 % = 0,80', '32 / 0,80 = 40'], check: 'El precio inicial debe ser mayor que 32 € porque hubo una rebaja.' },
    commonErrors: [{ code: 'wrong_reference_amount', trigger: { kind: 'numeric_value', value: 25.6, tolerance: 0.01 }, diagnosis: 'Ha calculado el 80 % de 32, tomando como referencia el precio ya rebajado.', feedback: '32 € no es el precio inicial: es el 80 % del precio inicial. No multipliques; divide entre 0,80.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2', 'MAT.2.A.5.3'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-005',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.compare_offers'],
    family: 'comparar_ofertas',
    difficulty: 3,
    statement: 'Tienda A: una chaqueta de 50 € con 20 % de descuento. Tienda B: la misma chaqueta de 48 € con 15 % de descuento. ¿En qué tienda queda más barata? Escribe el precio menor.',
    answerInput: { kind: 'text', placeholder: 'Ej.: 40 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 40, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'Calcula el precio final de cada tienda por separado.' },
      { level: 2, text: 'A: 50 − 20 % de 50. B: 48 − 15 % de 48.' },
      { level: 3, text: 'A queda en 40 €. B queda en 40,80 €.' },
    ],
    explanation: { text: 'En A se descuentan 10 € y se paga 40 €. En B se descuentan 7,20 € y se paga 40,80 €. La opción más barata es A: 40 €.', steps: ['A: 50 · 0,20 = 10; 50 − 10 = 40', 'B: 48 · 0,15 = 7,20; 48 − 7,20 = 40,80', '40 < 40,80'], check: 'Un descuento mayor no siempre basta: hay que mirar también el precio inicial.' },
    commonErrors: [{ code: 'ignores_units_or_context', trigger: { kind: 'numeric_value', value: 20, tolerance: 0.01 }, diagnosis: 'Ha elegido el porcentaje mayor como si fuera directamente el precio.', feedback: 'El 20 % no es un precio. Hay que calcular ambos precios finales antes de comparar.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE2', 'CE6', 'CE9'], criteria: ['2.2', '6.1', '9.2'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-006',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.strategy.repair_percent_reference'],
    family: 'reparacion_parte_total_final',
    difficulty: 1,
    statement: 'Reparación rápida: un libro cuesta 30 € y tiene un descuento del 10 %. Escribe solo cuánto se descuenta, no el precio final.',
    answerInput: { kind: 'text', placeholder: 'Ej.: 3 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 3, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'La pregunta pide la parte descontada.' },
      { level: 2, text: '10 % = 0,10. Multiplica 30 por 0,10.' },
    ],
    explanation: { text: 'El descuento es 30 · 0,10 = 3 €. El precio final sería 27 €, pero no era lo preguntado.', steps: ['10 % = 0,10', '30 · 0,10 = 3'], check: 'Si respondes 27 €, has calculado precio final, no descuento.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 27, tolerance: 0.01 }, diagnosis: 'Sigue confundiendo descuento con precio final.', feedback: 'Ese 27 € es el precio final. Vuelve a separar: descuento = parte que se quita; precio final = lo que se paga.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'F', knowledgeCodes: ['MAT.2.F.1.2', 'MAT.2.F.1.3'], competencies: ['CE9'], criteria: ['9.2'] },
    pedagogicalNotes: 'Ejercicio de reparación explícita para demostrar el diario de error útil del primer flujo.',
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-007',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.calculate_part'],
    family: 'porcentaje_parte_total',
    difficulty: 1,
    statement: 'Una sudadera cuesta 35 €. En una promoción hacen un 20 % de descuento. ¿Cuánto dinero te descuentan?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 7 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 7, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'El 20 % de 35 es 35 · 0,20 = 7 €. Eso es lo que se descuenta.', steps: ['20 % = 0,20', '35 · 0,20 = 7'], check: 'La rebaja tiene que ser menor que 35 €.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 28, tolerance: 0.01 }, diagnosis: 'Ha escrito el precio final y no la rebaja.', feedback: '28 € sería lo que pagas. La pregunta pide cuánto te descuentan.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2'], competencies: ['CE1', 'CE6'], criteria: ['1.3', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-008',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.final_price_after_change'],
    family: 'precio_final_descuento',
    difficulty: 2,
    statement: 'Un casco de bici cuesta 85 €. Tiene un descuento del 12 %. ¿Qué precio final pagas?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 74,80 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 74.8, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'Primero calculas la rebaja: 85 · 0,12 = 10,20 €. Luego restas al precio inicial: 85 − 10,20 = 74,80 €.', steps: ['12 % = 0,12', '85 · 0,12 = 10,20', '85 − 10,20 = 74,80'], check: 'Con descuento, el resultado debe ser menor que 85 €.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 10.2, tolerance: 0.01 }, diagnosis: 'Ha calculado solo la rebaja.', feedback: '10,20 € es la cantidad descontada. Falta hallar lo que se paga al final.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-009',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.calculate_total'],
    family: 'recuperar_precio_inicial',
    difficulty: 2,
    statement: 'Tras una rebaja del 25 %, un abrigo se queda en 54 €. ¿Cuál era el precio inicial?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 72 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 72, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'Si rebajan 25 %, pagas el 75 % del precio inicial.' },
      { level: 2, text: '54 € representa el 75 %. Divide entre 0,75.' },
    ],
    explanation: { text: 'Después de un 25 % de rebaja queda el 75 % del precio. Por tanto: precio inicial = 54 / 0,75 = 72 €.', steps: ['100 % − 25 % = 75 %', '75 % = 0,75', '54 / 0,75 = 72'], check: 'El precio inicial debe ser mayor que 54 €.' },
    commonErrors: [{ code: 'wrong_reference_amount', trigger: { kind: 'numeric_value', value: 40.5, tolerance: 0.01 }, diagnosis: 'Ha tomado 54 como referencia para volver a aplicar porcentaje.', feedback: '54 € ya es el precio rebajado. Debes deshacer la rebaja dividiendo entre 0,75.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-010' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.2', 'MAT.2.A.5.3'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.1', '1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-010',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.strategy.repair_percent_reference'],
    family: 'reparacion_referencia_correcta',
    difficulty: 2,
    statement: 'Reparación de referencia: si 54 € es el 75 % de un precio, ¿cuál es el precio total (100 %)?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 72 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 72, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'Para pasar de una parte al total, divide entre el porcentaje en decimal.' },
      { level: 2, text: 'Aquí el porcentaje es 75 % = 0,75.' },
    ],
    explanation: { text: 'Como 54 € representa el 75 %, para recuperar el 100 % se divide por 0,75. 54 / 0,75 = 72.', steps: ['75 % = 0,75', '54 / 0,75 = 72'], check: 'El resultado debe ser mayor que 54 €.' },
    commonErrors: [{ code: 'wrong_reference_amount', trigger: { kind: 'numeric_value', value: 40.5, tolerance: 0.01 }, diagnosis: 'Sigue multiplicando en vez de deshacer el porcentaje.', feedback: 'Multiplicar por 0,75 reduce. Para recuperar el total hay que dividir entre 0,75.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-010' }],
    curriculum: { sense: 'F', knowledgeCodes: ['MAT.2.F.1.2', 'MAT.2.F.1.3'], competencies: ['CE9'], criteria: ['9.2'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-011',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.compare_offers'],
    family: 'comparar_ofertas',
    difficulty: 3,
    statement: 'Oferta A: móvil de 240 € con 30 % de descuento. Oferta B: móvil de 210 € con 20 % de descuento. ¿Cuál deja menor precio final? Escribe ese precio.',
    answerInput: { kind: 'text', placeholder: 'Ej.: 168 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 168, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: [
      { level: 1, text: 'No compares solo porcentajes: calcula los dos precios finales.' },
      { level: 2, text: 'A: 240 − 30 % de 240. B: 210 − 20 % de 210.' },
      { level: 3, text: 'A queda en 168 € y B en 168 €.' },
    ],
    explanation: { text: 'En A: descuento 72 €, final 168 €. En B: descuento 42 €, final 168 €. Empatan: el precio menor es 168 € en ambas.', steps: ['A: 240 · 0,30 = 72; 240 − 72 = 168', 'B: 210 · 0,20 = 42; 210 − 42 = 168'], check: 'Puede ocurrir que dos ofertas distintas den el mismo precio final.' },
    commonErrors: [{ code: 'ignores_units_or_context', trigger: { kind: 'numeric_value', value: 30, tolerance: 0.01 }, diagnosis: 'Ha elegido el porcentaje mayor sin calcular precios finales.', feedback: 'Los porcentajes no se comparan solos: hay que convertir cada oferta a euros finales.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE2', 'CE6', 'CE9'], criteria: ['2.2', '6.1', '9.2'] },
  },
  {
    id: 'exercise.mv-2eso-a5-percentages-012',
    version: 1,
    source: { kind: 'created_for_mvp', extractionStatus: 'created' },
    course: '2ESO',
    subject: 'Matemáticas',
    moduleId: 'module.proportionality_finance',
    missionIds: ['mission.percentages.market_discounts'],
    nodeIds: ['node.percentages.final_price_after_change'],
    family: 'precio_final_iva',
    difficulty: 3,
    statement: 'Un patinete vale 300 € sin IVA. Con IVA del 21 %, ¿cuál es el precio final?',
    answerInput: { kind: 'text', placeholder: 'Ej.: 363 €' },
    expectedAnswer: { kind: 'number_with_unit', value: 363, unit: '€', tolerance: 0.01, unitRequired: false },
    correction: { corrector: 'numeric_with_unit', acceptedDecimalSeparators: [',', '.'], acceptEquivalentUnits: false },
    hints: commonPercentHints,
    explanation: { text: 'El IVA es 300 · 0,21 = 63 €. Sumando al precio base, 300 + 63 = 363 €.', steps: ['21 % = 0,21', '300 · 0,21 = 63', '300 + 63 = 363'], check: 'Con IVA, el precio final es mayor que el precio base.' },
    commonErrors: [{ code: 'parte_vs_final', trigger: { kind: 'numeric_value', value: 63, tolerance: 0.01 }, diagnosis: 'Ha calculado solo la parte del IVA.', feedback: '63 € es el IVA. La pregunta pide el total final: base + IVA.', repairExerciseId: 'exercise.mv-2eso-a5-percentages-006' }],
    curriculum: { sense: 'A', knowledgeCodes: ['MAT.2.A.2.5', 'MAT.2.A.5.2', 'MAT.2.A.5.3', 'MAT.2.A.6'], competencies: ['CE1', 'CE2', 'CE6'], criteria: ['1.3', '2.2', '6.1'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-001', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_one_step_add_subtract'], family: 'ecuacion_lineal_un_paso_suma_resta', difficulty: 1,
    statement: 'Resuelve: x + 7 = 15', answerInput: { kind: 'text', placeholder: 'Ej.: x = 8' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 8 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Resta 7 en ambos lados.' }, { level: 2, text: 'x = 15 - 7.' }], explanation: { text: 'x = 8.', check: 'Sustitución: 8 + 7 = 15.' }, commonErrors: [{ code: 'equations.inverse_operation_error', trigger: { kind: 'numeric_value', value: 22, tolerance: 0.01 }, feedback: 'Has sumado en vez de aplicar la operación inversa. Para quitar +7, resta 7.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-002', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_one_step_add_subtract'], family: 'ecuacion_lineal_un_paso_suma_resta', difficulty: 1,
    statement: 'Resuelve: x - 5 = -2', answerInput: { kind: 'text', placeholder: 'Ej.: 3' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 3 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Suma 5 en ambos lados.' }], explanation: { text: 'x = 3.', check: 'Sustitución: 3 - 5 = -2.' }, commonErrors: [{ code: 'equations.sign_error', trigger: { kind: 'numeric_value', value: -7, tolerance: 0.01 }, feedback: 'Revisa el signo: para deshacer -5 debes sumar 5.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-003', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_one_step_multiply_divide'], family: 'ecuacion_lineal_un_paso_producto_division', difficulty: 1,
    statement: 'Resuelve: 3x = 21', answerInput: { kind: 'text', placeholder: 'Ej.: x=7' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 7 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Divide entre 3.' }], explanation: { text: 'x = 7.', check: 'Sustitución: 3·7 = 21.' }, commonErrors: [{ code: 'equations.coefficient_division_error', trigger: { kind: 'numeric_value', value: 18, tolerance: 0.01 }, feedback: 'No se resta 3; se divide entre 3 para aislar x.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.1'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-004', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_one_step_multiply_divide'], family: 'ecuacion_lineal_un_paso_producto_division', difficulty: 2,
    statement: 'Resuelve: -4x = 20', answerInput: { kind: 'text', placeholder: 'Ej.: -5' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: -5 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Divide entre -4.' }], explanation: { text: 'x = -5.', check: 'Sustitución: -4·(-5)=20.' }, commonErrors: [{ code: 'equations.sign_error', trigger: { kind: 'numeric_value', value: 5, tolerance: 0.01 }, feedback: 'Positivo entre negativo da negativo. Revisa el signo final.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.2'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.1'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-005', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_two_step_basic'], family: 'ecuacion_lineal_dos_pasos', difficulty: 2,
    statement: 'Resuelve: 2x + 3 = 17', answerInput: { kind: 'text', placeholder: 'Ej.: 7' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 7 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Primero resta 3; luego divide entre 2.' }], explanation: { text: '2x = 14 y x = 7.', check: 'Sustitución: 2·7 + 3 = 17.' }, commonErrors: [{ code: 'equations.inverse_operation_error', trigger: { kind: 'numeric_value', value: 14, tolerance: 0.01 }, feedback: 'Has omitido dividir entre 2 después de restar 3.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.2'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.2'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-006', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.solve_two_step_basic'], family: 'ecuacion_lineal_dos_pasos', difficulty: 2,
    statement: 'Resuelve: 5x - 8 = 12', answerInput: { kind: 'text', placeholder: 'Ej.: x = 4' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 4 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Suma 8 y después divide entre 5.' }], explanation: { text: '5x = 20 y x = 4.', check: 'Sustitución: 5·4 - 8 = 12.' }, commonErrors: [{ code: 'equations.inverse_operation_error', trigger: { kind: 'numeric_value', value: 0.8, tolerance: 0.01 }, feedback: 'No restes 8 al segundo miembro; primero súmalo para deshacer -8.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.2'], competencies: ['CE2', 'CE4'], criteria: ['2.1', '4.2'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-007', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.algebra.check_solution_substitution'], family: 'comprobacion_por_sustitucion', difficulty: 3,
    statement: 'Resuelve: 4x + 2 = 26', answerInput: { kind: 'text', placeholder: 'Ej.: 6' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 6 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Resta 2 y luego divide entre 4.' }], explanation: { text: '4x = 24 y x = 6.', check: 'Sustitución: 4·6 + 2 = 26.' }, commonErrors: [{ code: 'equations.solution_not_checked', trigger: { kind: 'numeric_value', value: 24, tolerance: 0.01 }, feedback: '24 es el valor intermedio de 4x. Falta dividir entre 4 para hallar x y comprobar.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.3', 'MAT.2.D.6.1'], competencies: ['CE2', 'CE6'], criteria: ['4.2', '6.2'] },
  },
  {
    id: 'exercise.mv-2eso-d4-equations-008', version: 1, source: { kind: 'created_for_mvp', extractionStatus: 'created' }, course: '2ESO', subject: 'Matemáticas', moduleId: 'module.algebra_equations_functions', missionIds: ['mission.algebra.linear_equations_brief'], nodeIds: ['node.strategy.repair_inverse_operation'], family: 'reparacion_operacion_inversa', difficulty: 3,
    statement: 'Resuelve: 3x - 4 = 14', answerInput: { kind: 'text', placeholder: 'Ej.: x = 6' }, expectedAnswer: { kind: 'linear_equation_solution', variable: 'x', value: 6 }, correction: { corrector: 'linear_equation_solution', acceptBareNumber: true, validateBySubstitution: true },
    hints: [{ level: 1, text: 'Suma 4 y después divide entre 3.' }, { level: 2, text: 'Este ejercicio activa la carta: sustituye antes de seguir.' }], explanation: { text: '3x = 18; x = 6.', check: 'Sustitución: 3·6 - 4 = 14.' }, commonErrors: [{ code: 'equations.inverse_operation_error', trigger: { kind: 'numeric_value', value: 10, tolerance: 0.01 }, feedback: 'Has restado 4 en vez de sumarlo para deshacer -4. Corrige el orden y luego divide entre 3.' }],
    curriculum: { sense: 'D', knowledgeCodes: ['MAT.2.D.4.3', 'MAT.2.D.6.1'], competencies: ['CE2', 'CE6', 'CE8'], criteria: ['4.2', '6.2', '8.1'] },
  },
];

export const contentSeed: ContentSeed = {
  contentVersion: CONTENT_VERSION,
  modules,
  missions,
  skillNodes,
  theoryCards,
  exercises,
};
